### Create Product

POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
  "id" : "A0010",
  "name" : "Mac Book Pro 15",
  "price" : 30000000,
  "quantity" : 10
}

### Create Product Invalid

POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
"id" : "",
"name" : "",
"price" : 0,
"quantity" : -10
}

### Get Product

GET http://localhost:8080/api/product/A0001
Accept: application/json

### Get Product not found

GET http://localhost:8080/api/products/Salah
Accept: application/json

### Update Product

PUT http://localhost:8080/api/products/A0001
Content-Type: application/json
Accept: application/json

{
  "name" : "Apple Mac Book Pro 15 2020",
  "price": 40000000,
  "quantity": 100
}

### Update Product not found

PUT http://localhost:8080/api/products/Salah
Content-Type: application/json
Accept: application/json

{
  "name" : "Apple Mac Book Pro 15 2020",
  "price": 40000000,
  "quantity": 100
}

### Update Product with invalid body

PUT http://localhost:8080/api/products/A0001
Content-Type: application/json
Accept: application/json

{
  "name" : "",
  "price": 0,
  "quantity": -10
}

### Delete Product

DELETE http://localhost:8080/api/products/A0001
Accept: application/json

### List Product

GET http://localhost:8080/api/products
Accept: application/json

### List Product with size parameter

GET http://localhost:8080/api/products?size=5
Accept: application/json

### List Product with size and page parameter

GET http://localhost:8080/api/products?size=5&page=1
Accept: application/json